In [1]:
# импорт необходимых библиотек
import pandas as pd
import numpy as np
from tqdm import tqdm
tqdm.pandas()
import re
import ast
from Levenshtein import distance

In [2]:
# чтение файла
data = pd.read_csv('data/dataset.csv', sep=',')

# 6 city

In [3]:
data['city'].unique()[:15]

array(['Southern Pines', 'Spokane Valley', 'Los Angeles', 'Dallas',
       'Palm Bay', 'Philadelphia', 'POINCIANA', 'Memphis', 'Mason City',
       'Houston', 'Flushing', 'Pembroke Pines', 'Eugene', 'Brooklyn',
       'Fort Lauderdale'], dtype=object)

In [4]:
print('Количество уникальных значений: ', data['city'].nunique())

Количество уникальных значений:  2026


In [5]:
# создаем список всех уникальных значений в столбце
unique_values = data['city'].unique()

# создаем список всех уникальных значений в столбце, приведенных к нижнему регистру
lowercase_values = [str(value).lower() if isinstance(value, str) else str(value) for value in unique_values]

# создаем словарь синонимов (ключ - это нормализованное значение, значение - это список всех значений, которые считаются синонимами)
synonyms_dict = {}

for value in unique_values:
    # нормализуем текущее значение
    normalized_value = str(value).lower() if isinstance(value, str) else str(value)

    # ищем все значения, которые считаются синонимами для текущего значения
    synonyms = [v for v in unique_values if distance(str(v).lower() if isinstance(v, str) else str(v), normalized_value) <= 1]

    # добавляем текущее значение и его синонимы в словарь
    synonyms_dict[normalized_value] = synonyms

# выводим все найденные синонимы
for key, value in synonyms_dict.items():
    if len(value) > 1:
        print(f"Synonyms for '{key}': {value}")

Synonyms for 'los angeles': ['Los Angeles', 'Los angeles']
Synonyms for 'dallas': ['Dallas', 'DALLAS']
Synonyms for 'poinciana': ['POINCIANA', 'Poinciana']
Synonyms for 'new york': ['New York', 'New york']
Synonyms for 'bend': ['Bend', 'BEND']
Synonyms for 'spring': ['Spring', 'Springs']
Synonyms for 'miami': ['Miami', 'MIAMI']
Synonyms for 'davie': ['Davie', 'Davis']
Synonyms for 'tampa': ['Tampa', 'TAMPA']
Synonyms for 'jacksonville': ['Jacksonville', 'JACKSONVILLE']
Synonyms for 'charlotte': ['Charlotte', 'CHARLOTTE']
Synonyms for 'rotonda west': ['ROTONDA WEST', 'Rotonda West']
Synonyms for 'weston': ['Weston', 'Reston']
Synonyms for 'fort worth': ['Fort Worth', 'Fort worth']
Synonyms for 'temple terrace': ['Temple Terrace', 'TEMPLE TERRACE']
Synonyms for 'atlanta': ['Atlanta', 'Atlaanta']
Synonyms for 'lakewood': ['Lakewood', 'LAKEWOOD']
Synonyms for 'seattle': ['Seattle', 'SEATTLE']
Synonyms for 'port charlotte': ['PORT CHARLOTTE', 'Port Charlotte']
Synonyms for 'saint johns': ['

Необходимо привести названия городов к одинаковому регистру

In [6]:
data['city'] = data['city'].apply(lambda x: x.lower() if isinstance(x, str) else x)

In [7]:

# создаем список всех уникальных значений в столбце
unique_values = data['city'].unique()

# создаем список всех уникальных значений в столбце, приведенных к нижнему регистру
lowercase_values = [str(value).lower() if isinstance(value, str) else str(value) for value in unique_values]

# создаем словарь синонимов (ключ - это нормализованное значение, значение - это список всех значений, которые считаются синонимами)
synonyms_dict = {}

for value in unique_values:
    # нормализуем текущее значение
    normalized_value = str(value).lower() if isinstance(value, str) else str(value)

    # ищем все значения, которые считаются синонимами для текущего значения
    synonyms = [v for v in unique_values if distance(str(v).lower() if isinstance(v, str) else str(v), normalized_value) <= 1]

    # добавляем текущее значение и его синонимы в словарь
    synonyms_dict[normalized_value] = synonyms

# выводим все найденные синонимы
for key, value in synonyms_dict.items():
    if len(value) > 1:
        print(f"Synonyms for '{key}': {value}")

Synonyms for 'spring': ['spring', 'springs']
Synonyms for 'davie': ['davie', 'davis']
Synonyms for 'weston': ['weston', 'reston']
Synonyms for 'atlanta': ['atlanta', 'atlaanta']
Synonyms for 'valley view': ['valley view', 'valleyview']
Synonyms for 'mckinney': ['mckinney', 'mc kinney']
Synonyms for 'austin': ['austin', 'tustin']
Synonyms for 'nashville': ['nashville', 'ashville']
Synonyms for 'st petersburg': ['st petersburg', 'st. petersburg']
Synonyms for 'bryan': ['bryan', 'bryant']
Synonyms for 'irving': ['irving', 'irvine']
Synonyms for 'swanton': ['swanton', 'stanton']
Synonyms for 'asheville': ['asheville', 'ashville']
Synonyms for 'brooksville': ['brooksville', 'crooksville']
Synonyms for 'forest hills': ['forest hills', 'forest hill']
Synonyms for 'ashville': ['nashville', 'asheville', 'ashville']
Synonyms for 'irvine': ['irving', 'irvine']
Synonyms for 'chino': ['chino', 'chico', 'china']
Synonyms for 'soddy daisy': ['soddy daisy', 'soddy-daisy']
Synonyms for 'bellingham': ['

In [8]:
# Создаем словарь с заменами
replacements_city = {
    'springs,': 'spring',
    'davis': 'davie',
    'reston': 'weston',
    'atlaanta': 'atlanta',
    'valleyview': 'valley view',
    'mc kinney': 'mckinney',
    'tustin': 'austin',
    'ashville': 'nashville',
    'st. petersburg': 'st petersburg',
    'bryant': 'bryan',
    'irvine': 'irving',
    'stanton': 'swanton',
    'asheville': 'nashville',
    'chico': 'chino',
    'china': 'chino',
    'soddy-daisy': 'soddy daisy',
    'belllingham': 'bellingham',
    'st. johns': 'st johns',
    'aventura': 'ventura',
    'oklawaha': 'ocklawaha',
    'clifton': 'clinton',
    'silver spring': 'silver springs',
    'rossville': 'roseville',
    'arrington': 'arlington',
    'commercecity': 'commerce city',
    'denton': 'renton',
    'trenton': 'renton',
    'reston': 'renton',
    'inglewood': 'englewood',
    'panton': 'canton',
    'canyon': 'canton',
    'delton': 'renton',
    'youngtown': 'youngstown',
    'morrison': 'morristown',
    'morriston': 'morristown',
    'reading': 'redding',
    'fairfield twp.': 'fairfield twp',
    'silver springs': 'silver spring',
    'opa-locka': 'opa locka',
    'wheatridge': 'wheat ridge',
    'alden': 'allen',
    'maxville': 'mayville',
    'silver lakes': 'silver lake',
    'willsboro': 'hillsboro',
    'bedford': 'redford',
    'medford': 'redford',
    'milwaukee': 'milwaukie',
    'federal heights': 'federalheights',
    'bee caves': 'bee cave',
    'dalton': 'dayton',
    'stow': 'stowe',
    'forest hills': 'forest hill',
    'brookpark': 'brook park',
    'powell': 'lowell',
    'mercer': 'merced',
    'roseville': 'rossville',
    'doctor philips': 'doctor phillips',
    'arrington': 'barrington',
    'mc allen': 'mcallen',
    'st albans city': 'st. albans city',
    'deltona': 'renton',
    'belton': 'renton',
    'dolton': 'renton',
    'ft. worth': 'ft worth',
    'mill creek': 'millcreek',
    'st. george': 'st george',
    'onon hill': 'oxon hill',
    'arden': 'allen',
    'belmond': 'belmont',
    'mcgregor': 'mc gregor',
    'lake forest': 'wake forest',
    'nome': 'rome',
    'rowe': 'rome',
    'ruston': 'reston',
    'leona valley': 'leon valley',
    'troy': 'roy',
    'biola': 'iola',
     'highlands': 'highland',
    'green acres': 'greenacres',
    'downs': 'dows',
    'bryant': 'brant',
    'unincorporated broward county': 'un-incorporated broward county',
    '': None,
    'no data': None,
    'none': None
    }


# Заменяем значения в столбце "sity" с помощью словаря замен
data['city'].replace(replacements_city, inplace=True)

In [9]:
print('Количество уникальных значений: ', data['city'].nunique())

Количество уникальных значений:  1836


In [10]:
print('Доля (%) 300 наиболее весомых категорий: ' , round((data['city'].value_counts().nlargest(300)/len(data)*100).sum(),1))

Доля (%) 300 наиболее весомых категорий:  90.5


In [11]:
city_list = list(data['city'].value_counts().nlargest(300).index)
data['city'] = data['city'].progress_apply(lambda x: x if x in city_list else 'other')

100%|██████████| 377185/377185 [00:00<00:00, 438045.28it/s]


# 7 schools

Посмотрим на данные

In [12]:
data['schools'][2]

"[{'rating': ['8/10', '4/10', '8/10'], 'data': {'Distance': ['1.19mi', '2.06mi', '2.63mi'], 'Grades': ['6-8', 'K-5', '9-12']}, 'name': ['Paul Revere Middle School', 'Brentwood Science School', 'Palisades Charter High School']}]"

Разобьем строку на отдельные словари

In [13]:
facts = ast.literal_eval(data['schools'][0])
for fact in facts:
    print (fact)
print (facts)

{'rating': ['4', '4', '7', 'NR', '4', '7', 'NR', 'NR'], 'data': {'Distance': ['2.7 mi', '3.6 mi', '5.1 mi', '4.0 mi', '10.5 mi', '12.6 mi', '2.7 mi', '3.1 mi'], 'Grades': ['3–5', '6–8', '9–12', 'PK–2', '6–8', '9–12', 'PK–5', 'K–12']}, 'name': ['Southern Pines Elementary School', 'Southern Middle School', 'Pinecrest High School', 'Southern Pines Primary School', "Crain's Creek Middle School", 'Union Pines High School', 'Episcopal Day Private School', 'Calvary Christian Private School']}
[{'rating': ['4', '4', '7', 'NR', '4', '7', 'NR', 'NR'], 'data': {'Distance': ['2.7 mi', '3.6 mi', '5.1 mi', '4.0 mi', '10.5 mi', '12.6 mi', '2.7 mi', '3.1 mi'], 'Grades': ['3–5', '6–8', '9–12', 'PK–2', '6–8', '9–12', 'PK–5', 'K–12']}, 'name': ['Southern Pines Elementary School', 'Southern Middle School', 'Pinecrest High School', 'Southern Pines Primary School', "Crain's Creek Middle School", 'Union Pines High School', 'Episcopal Day Private School', 'Calvary Christian Private School']}]


Cоздадим функцию для извлечения характеристик, принимая во внимание формат: количество школ, а также минимальный, средний и максимальный рейтинг школ и расстояние до школы

In [14]:
def get_float(string):
    a = re.findall(r"[-+]?(?:\d*\.*\d+)", str(string).replace(',', '.'))
    if a != []:
        b = float(a[0])
        return b
    else:
        return np.nan

In [15]:
def schools_feature (x):
    
    x =  ast.literal_eval(x)
    schools = pd.json_normalize(x)
            
    len_list = []
    for i in range(0,4):
        len_list.append(len(schools.iloc[0][i]))
    mx = max(len_list)
    
    for col in list(schools.columns):
        while len(schools[col][0]) < mx:
            schools[col].iloc[0].append(np.nan)
            
    schools = schools.explode(['rating','name','data.Distance', 'data.Grades'])
       

    if len(schools['rating']) == 1 and schools['rating'][0] is np.nan:
        Min_rating, Max_rating, Mean_rating = np.nan, np.nan, np.nan
    else: 
        schools['rating'] = schools['rating'].apply(get_float)
        Min_rating, Max_rating, Mean_rating = schools['rating'].min(), schools['rating'].max(), schools['rating'].mean()

        
    if len(schools['data.Distance']) == 1 and schools['data.Distance'][0] is np.nan:
        Min_distance, Max_distance, Mean_distance = np.nan, np.nan, np.nan
    else: 
        schools['data.Distance'] = schools['data.Distance'].apply(get_float)
        Min_distance, Max_distance, Mean_distance = schools['data.Distance'].min(), schools['data.Distance'].max(), schools['data.Distance'].mean()

    return len(schools), Min_rating, Max_rating, Mean_rating, Min_distance, Max_distance, Mean_distance

    
school_feature_list = ['Number of schools', 'Min rating', 'Max rating', 'Mean rating', 'Min distance', 'Max distance', 'Mean distance']
  
data [['Number of schools', 'Min rating','Max rating','Mean rating','Min distance','Max distance','Mean distance']] = data['schools'].progress_apply(schools_feature).apply(pd.Series)

  0%|          | 0/377185 [00:00<?, ?it/s]

100%|██████████| 377185/377185 [39:03<00:00, 160.92it/s] 


In [16]:
data = data.drop('schools', axis =1)

# 8 sqft

In [17]:
data['sqft'].unique()[:15]

array(['2900', '1,947 sqft', '3,000 sqft', '6,457 sqft', nan, '897 sqft',
       '1,507', '3588', '1,930', '1,300 sqft', '3,130', '2,839 sqft',
       'Total interior livable area: 1,820 sqft', '2,454', '2,203'],
      dtype=object)

In [18]:
data['sqft'] = data['sqft'].progress_apply(get_float)

100%|██████████| 377185/377185 [00:01<00:00, 251102.81it/s]


In [19]:
data['sqft'].unique()[:15]

array([2.900e+03, 1.947e+00, 3.000e+00, 6.457e+00,       nan, 8.970e+02,
       1.507e+00, 3.588e+03, 1.930e+00, 1.300e+00, 3.130e+00, 2.839e+00,
       1.820e+00, 2.454e+00, 2.203e+00])

# 9 zipcode

In [20]:
data['zipcode'].unique()[:15]

array(['28387', '99216', '90049', '75205', '32908', '19145', '34759',
       '38115', '50401', '77080', '11354', '77068', '33028', '97401',
       '77084'], dtype=object)

In [21]:
print('Количество уникальных значений: ', data['zipcode'].nunique())

Количество уникальных значений:  4549


# 10 beds

In [22]:
data['beds'].unique()[:100]

array(['4', '3 Beds', '5 Beds', nan, '2 Beds', '3', '4 Beds', '3 bd',
       'Baths', '4 bd', '5 bd', '8 Beds', '2', '2 bd', '2.0', '5', '1',
       '3.0', '6 Beds', 'Bath', '12 Beds', '6', '14', '0.25 acres',
       '6 bd', '-- bd', '7', '5.0', '4.0', ' ', '7 Beds', '1 bd',
       '9 Beds', '0.44 acres', '0', '1.43 acres', '0.32 acres',
       '8,637 sqft', '7.0', '8', '16 Beds', '9.7 acres', '1.0', '16 bd',
       '10,310 sqft', '6,250 sqft', '3.02 acres', '2 acres', '5,000 sqft',
       '0.96 acres', '6.0', '13 bd', '6.31 acres', '0.6 acres', '9',
       '5,662 sqft', '2,200 sqft', '10', '18 Beds', '10 Beds',
       '0.46 acres', '0.59 acres', '20 Beds', '0.0', '2,874 sqft',
       '0.26 acres', '10 bd', '32', '0.4 acres', '2,178 sqft',
       '6,351 sqft', '4,356 sqft', '5 acres', '0.55 acres', '5,501 sqft',
       '8,001 sqft', '0.7 acres', '1.69 acres', '0.88 acres',
       '0.34 acres', '13 Beds', '1.5 acres', '0.97 acres', '7,405 sqft',
       '7 bd', '8.43 acres', '1,502 sqft'

In [23]:
data['beds'] = data['beds'].progress_apply(get_float)
data['beds'] = data['beds'].progress_apply(lambda x: x if  (1<= x <1000 and x.is_integer()) else np.nan)

100%|██████████| 377185/377185 [00:00<00:00, 738079.58it/s]


In [24]:
data['beds'].unique()[:100]

array([  4.,   3.,   5.,  nan,   2.,   8.,   1.,   6.,  12.,  14.,   7.,
         9.,  16.,  13.,  10.,  18.,  20.,  32.,  11.,  26.,  64., 144.,
        22.,  24.,  15.,  28.,  60.,  36.,  19.,  48.,  25.,  17.,  27.,
        37.,  40.,  47.,  23.,  44.,  30.,  33.,  38.,  31.,  34., 831.,
       248.,  99., 184.,  78., 542.,  53.,  50.,  51., 102.,  21., 106.,
        75.,  29., 640., 449., 448., 100.,  39.,  52.,  42., 150., 540.,
        46., 871.,  76.,  35.,  88., 840.])

# 11 state

In [25]:
data['state'].unique()[:15]

array(['NC', 'WA', 'CA', 'TX', 'FL', 'PA', 'TN', 'IA', 'NY', 'OR', 'DC',
       'NV', 'AZ', 'GA', 'IL'], dtype=object)

In [26]:
print('Количество уникальных значений: ', data['state'].nunique())

Количество уникальных значений:  39


# 12 stories

In [27]:
data['stories'].unique()[:100]

array([nan, '2.0', '1.0', '3.0', 'One', '2', 'Multi/Split', '4.0', '0.0',
       '0', 'One Level', '1', '9.0', '3', '1 Level, Site Built',
       'One Story', '3.00', '1.00', '14.0', 'Two', '3+', '1 Story', '5.0',
       '2 Story', 'Ranch/1 Story', 'Condominium', 'Stories/Levels', '7.0',
       '2 Level, Site Built', '2 Level', '15', '3 Level, Site Built', '4',
       '22.0', '2.00', '6.0', '1.0000', 'Lot', '3 Story', 'Three Or More',
       '1.5', '1 Level', 'Two Story or More', 'Site Built, Tri-Level',
       '54.0', '23', 'Farm House', '8.0', '16.0', '1.50', '18', '9', '21',
       '8', '12.0', 'Split Level w/ Sub', '11.0', '18.0', '1.5 Stories',
       '7', '11', 'Townhouse', '12', '21.0', '16', '1.5 Story/Basement',
       '28.0', 'Traditional', '2.5 Story', '17', '2.0000', '63.0',
       'Acreage', 'Ground Level, One', '6', 'Split Foyer', '2 Stories',
       '27.0', '19.0', '2.50', '1.30', '2 Story/Basement', 'Split Level',
       '1.5 Story', '1.5 Level', '2 Or More Stories',
  

В признаке разношерстные данные, к тому же пропуски составляют почти 40%. Удалим данный признак.

In [28]:
data = data.drop('stories', axis=1)

# 13 mls-id и MLsId

Данный признак не несет информации, влияющей на стоимость жилья, поэтому удалим его.

In [29]:
data = data.drop('mls-id', axis=1)

In [30]:
data = data.drop('MlsId', axis=1)

# 14 street

In [31]:
data = data.drop('street', axis=1)

# 15 fireplace

Данный признак содержит почти 73% пропусков. Удалим его.

In [32]:
data = data.drop('fireplace', axis=1)

# 16 target

In [33]:
data['target'].unique()[:50]

array(['$418,000', '$310,000', '$2,895,000', '$2,395,000', '$5,000',
       '$209,000', '181,500', '68,000', '$244,900', '$311,995',
       '$669,000', '260,000', '$525,000', '$499,900', '$168,800',
       '1,650,000', '335,000', '2,650,000', '$365,000', '$626,000',
       '$375,000', '$3,500,000', '579,000', '$499,007', '$182,000',
       '$3,749,000', '799,000', '$559,000', '$830,000', '$1,195,000',
       '$262,000', '$204,800', '$179,000', '$105,000', '$260,000',
       '$284,900', '$495,000', '$117,900', '$385,000', '54,000',
       '$1,100,000', '850,000', '$620,000', '$125,000', '$499,000',
       '$1,429,000', '$233,990+', '125,000', '$275,000', '$27,000'],
      dtype=object)

In [34]:
print('Количество уникальных значений: ', data['target'].nunique())

Количество уникальных значений:  43939


In [35]:
data['target'] = data['target'].progress_apply(get_float)

100%|██████████| 377185/377185 [00:01<00:00, 285725.22it/s]


In [36]:
data['target'].unique()[:50]

array([418.   , 310.   ,   2.895,   2.395,   5.   , 209.   , 181.5  ,
        68.   , 244.9  , 311.995, 669.   , 260.   , 525.   , 499.9  ,
       168.8  ,   1.65 , 335.   ,   2.65 , 365.   , 626.   , 375.   ,
         3.5  , 579.   , 499.007, 182.   ,   3.749, 799.   , 559.   ,
       830.   ,   1.195, 262.   , 204.8  , 179.   , 105.   , 284.9  ,
       495.   , 117.9  , 385.   ,  54.   ,   1.1  , 850.   , 620.   ,
       125.   , 499.   ,   1.429, 233.99 , 275.   ,  27.   , 598.   ,
         1.78 ])

In [37]:
data.head()

Unnamed: 0.1  Unnamed: 0    status   propertyType  baths            city  \
0             0           0    active  single family    3.5  southern pines   
1             1           1  for sale  single family    3.0           other   
2             2           2  for sale  single family    2.0     los angeles   
3             3           3  for sale  single family    8.0          dallas   
4             4           4  for sale           land    NaN        palm bay   

       sqft zipcode  beds state  ...  Year built  Remodeled year Price/sqft  \
0  2900.000   28387   4.0    NC  ...         3.0             NaN      144.0   
1     1.947   99216   3.0    WA  ...         3.0             NaN      159.0   
2     3.000   90049   3.0    CA  ...        61.0            55.0      965.0   
3     6.457   75205   5.0    TX  ...        16.0            16.0      371.0   
4       NaN   32908   NaN    FL  ...         NaN             NaN        NaN   

   Number of schools Min rating Max rating  Mean rating  Min distance  \
0                8.0        4.0        7.0     5.200000          2.70   
1                3.0        4.0       10.0     6.000000          1.01   
2                3.0        4.0        8.0     6.666667          1.19   
3                4.0        9.0       10.0     9.250000          0.10   
4                3.0        4.0        5.0     4.666667          3.03   

   Max distance  Mean distance  
0         12.60       5.537500  
1          1.65       1.326667  
2          2.63       1.960000  
3          1.05       0.752500  
4          5.96       4.080000  

[5 rows x 26 columns]

In [38]:
data.to_csv('df.csv')